### ISSUE TITLE
Video not included on wiki

### ISSUE THREAD

**Issue by 130s** [ros-industrial-consortium/reuleaux#29]
http://wiki.ros.org/reuleaux#Overview states about a video but it seems to be missing :)

**Comment by jontromanab** [comment]
@130s Thank you very much for notifying that. Yes. It is missing. Will try to include as soon as possible. :( Forgot to do that.

**Comment by jontromanab** [comment]
@130s Thank you very much for notifying that. Yes. It is missing. Will try to include as soon as possible. Forgot to do that.

**Comment by 130s** [comment]
Friendly ping :)

I googled to no avail, though I thought saw a video somewhere. Was it during a dev meeting?

**Comment by Levi-Armstrong** [comment]
@akgoins, Do you by chance have a copy of the video?

**Comment by jontromanab** [comment]
@akgoins if you have the video please share it, I can upload it to the [wiki](http://wiki.ros.org/reuleaux#Overview)
Anyways I will be making a video in couple of days.

**Comment by scottpaulin** [comment]
Another friendly ping :). Would also love to see a video of this package in action!

**Comment by jontromanab** [comment]
Hello @130s , @Levi-Armstrong , @scottpaulin The Reuleaux package now has a video with modified functionalities. Please have a look.

**Comment by 130s** [comment]
Cool, thanks!
