### ISSUE TITLE
[Q] How to specify the target robot (model file) upon creating the reachability map?

### ISSUE THREAD

**Issue by 130s** [ros-industrial-consortium/reuleaux#43]
As per title. I followed http://wiki.ros.org/reuleaux but I haven't got a map.

(The robot package I'm thinking of already has OpenRave package so I skipped chapter 3.)

**Comment by geoffreychiou** [comment]
I think you copy your robot_ikfast.cpp file into map_creator/include/ and modify
https://github.com/ros-industrial-consortium/reuleaux/blob/master/map_creator/include/map_creator/kinematics.h by commenting out 
```
#include "mh5_ikfast.cpp"
``` 
and replacing it with your new file.

**Comment by jontromanab** [comment]
@130s Can you let me know which robot you are thinking of?
I have repository of various robots ikfast files. May be I can send you the one you need.

Lets' go through your problem step-by-step:

Have you completed this step? **3.3 Setting up Kinematics for the robot**
Here you have move <your_robot_ikfast>.cpp file to the map_creator/included/map_creator folder and update the kinematics.h file by putting **#include "your_robot_ikfast.cpp"** and commenting **#include "mh5_ikfast.cpp"**

Please have a look at the other open pull request of mine. Where UR5, ABB and other robots are incorporated. Or here

https://github.com/jontromanab/reuleaux/tree/robot_visualization/map_creator/include/map_creator

By the way, did your package built a map? (it should have built one for mh5 robot if you have not changed anything) It can be visualized easily.  ==> Mentioned in the ros wiki
Please let me know. Hope I can resolve your problem.

**Comment by 130s** [comment]
Ok, at least my question in the subject line is answered, thanks.
