### ISSUE TITLE
Cannot load reachibility map

### ISSUE THREAD

**Issue by akashpatil92** [ros-industrial-consortium/reuleaux#47]
Hello @jontromanab , I was creating reachibility map for UR10 robot and was successful for generating ikfast cpp file for the same.I also created reachibility map from that ikfast cpp which was of 111 MB(I am doubtful about this file size for h5 map since rest map file sizes are quiet small). I get following error while loading this reachibility map.

[ INFO] [1492671170.055510703]: Opening map ur10_robot.h5
Segmentation fault (core dumped)
 Kindly help as soon as possible regarding this issue.I installed latest openrave which is of version no. 0.9.I have ROS Indigo running on my system.

**Comment by jontromanab** [comment]
Hello @akashpatil92 . Yes, the size seems suspicious. Can you please send me the link from where I can access the ikfast.cpp file and reproduce the error? BTW, how much time did it take to make the h5 map?

**Comment by akashpatil92** [comment]
[IKFast UR10.tar.gz](https://github.com/ros-industrial-consortium/reuleaux/files/946106/IKFast.UR10.tar.gz)
Hello @jontromanab  I have attached IKfast cpp file in compressed folder in above link.Kindly check it.
I would like to narrate you scenerio which I faced during whole file creation.
1. I went through your tutorial [http://wiki.ros.org/reuleaux](url) and then tried to execute this command 
  sudo apt-get install openrave0.8-dp-ikfast  which said me my system cannot locate package.So I went to openrave website for installation and installed openrave 0.8 and in sequence executed this command python `openrave-config --python-dir`/openravepy/_openravepy_/ikfast.py --robot=<myrobot_name>.dae --iktype=transform6d --baselink=1 --eelink=8 --savefile=<ikfast_output_path>  which worked for approx 10 min and then threw python error : maximum recursion depth exceeded. So I referred over here [https://sourceforge.net/p/openrave/mailman/message/35357692/](url) which said to install openrave from source and checkout to some old commit.
2. Then I installed openrave from that commit and then didnt got maximum recursion depth exceeded error.But faced this issue of segmentation fault while loading map.
 It took me approx 45 minutes to generate h5 map file as well as to generate ikfast cpp file.

**Comment by jontromanab** [comment]
[ur10_maps.tar.gz](https://github.com/ros-industrial-consortium/reuleaux/files/946726/ur10_maps.tar.gz)
Hello @akashpatil92 The time takes to create ikfast file is not really in my hand.
But to my surprise, your ikfast file which is only 3.3mb works absolutely file. I have created 3 reachability maps with your file with resolutions 0.1, 0.2, 0.08. This is the size and time taken to generate those:

0.1 => 1.8mb => 25.15s
0.2 => 14mb  => 196.90s
0.08 => 27.2mb => 418.62s

The UR robots seems very precise about finding reachable poses in every spheres. So it takes a little bit longer time. But with the default values 418.62s is pretty decent compared to openrave reachability maps which may take upto 4-5 hours.

Please let me know if this works for you. If you still have problem creating maps, I can help you in other ways.

**Comment by akashpatil92** [comment]
Thanks @jontromanab  I tried with resolution 0.1 and it worked good. I came across the issue when I used resolution 0.05 as per your tutorial. So basically resolution was the issue. And it took 162 secs for me to generate map with resolution 0.1. My guess is this time varies as per system configuration which you are using.

**Comment by jontromanab** [comment]
Yes @akashpatil92 . The time is dependent on system configuration. The 0.05 resolution is too high. Most probably you will not need such amount of poses. IT will also create problems for other applications using the map. For our experiments, I found that 0.1 or 0.08 is enough. Good to hear that you problem got solved. You can close this issue now if you like.

**Comment by akashpatil92** [comment]
Yes @jontromanab . I am closing this issue.Thanks for the help.
