### ISSUE TITLE
plugin.xml has no root element

### ISSUE THREAD

**Issue by asaksena1978** [ros-industrial-consortium/reuleaux#53]
while starting rviz I get this error - "skipped loading plugin with error: XML Documents '<PATH>/reuleaux/base_placement_plugin/plugin.xml' has no Root Element. This likely means the XML is malformed or missing.."
I checked base_placement_pluigin folder plugin.xml file exists.
rviz is running, but the reachability map is not displayed.

**Comment by jontromanab** [comment]
I dont think its an error. It can be an warning. Have you tried to visualize the map by following the tutorial. Also referenced here #46 
Please let me know

**Comment by asaksena1978** [comment]
I was able to fix the error by closing the '/class' in plugin.xml and changing fixed frame to base_link as suggested by you #46. Now I am able to view the reachability map.

**Comment by jontromanab** [comment]
@gavanderhoorn I have added the missing closing tag in PR #54 
Thank you for watching out.
