### ISSUE TITLE
Workspace show a box with robots with a higher structure like KUKA-KR210L150 o FANUC-r1000ia80f

### ISSUE THREAD

**Issue by myalfred03** [ros-industrial-consortium/reuleaux#56]
Hello, I've follow all steps how to generate the workspace of Robots, I've test robots like MH5 of tutorial and irb120 and  the workspace is fine, but when test the robots like KUKA-KR210L150 o FANUC-r1000ia80f this show me a box that don't match with the real workspace of a robot of 6DOF

![urdf rviz- - rviz_186](https://user-images.githubusercontent.com/12577091/49748124-8309f180-fc6a-11e8-8cfc-6c3c41a6cffb.png)

I've check the file **create_reachability_map.cpp** in the line 90 show info in the comments that a box is created is the **1** meters? 
If I edit the parameters is the optimum for my workspace? :)

![image](https://user-images.githubusercontent.com/12577091/49748583-aed9a700-fc6b-11e8-8ded-10dc1364fb0d.png)

**Comment by jontromanab** [comment]
yes, Please change the parameter in the line 98 (float r = 1) try to put 2 and rerun it. (1 is the approximation of initial box around the robot) If your robot is bigger, you should consider bigger approximation.

**Comment by myalfred03** [comment]
Thanks @jontromanab, this way is workspace acceptable?, if is ok them I would Close the issue.

**Comment by jontromanab** [comment]
Yes, that is the way to approximate the initial box size (ps. I dont know your robot's size, so may be you have to tweak that parameter)

**Comment by myalfred03** [comment]
Thanks @jontromanab :+1:
