### ISSUE TITLE
issue for reachability map visualizing in ros noetic

### ISSUE THREAD

**Issue by Erixar** [ros-industrial-consortium/reuleaux#65]
There are some problems when i was tried to visualizing the reachability map in rviz as tutorial , there just... nothing happend.
the file I've chosen is the demo https://github.com/jontromanab/ikfast_and_reach_maps.git  
When i started with _rosrun map_creator load_reachability_map abb_irb2400_r0.09_reachability.h5 
the terminal just shows [ INFO] [1640604031.604953992]: Opening map abb_irb2400_r0.09_reachability.h5_
and that's what happend in rviz
![img](https://user-images.githubusercontent.com/71119403/147469198-b860ac5c-30fd-40a4-9470-4e14a9718a25.PNG)

I'm new of ROS, and i have no idea about that. is that because i'm using noetic?

**Comment by ichdich** [comment]
You'd better set Fixed Frame to base_link instead of map.

**Comment by juntuck** [comment]
I ran into the same problem. Just remove the slash in [this line](https://github.com/ros-industrial-consortium/reuleaux/blob/ad33a164d2e81bdbb79c2aa6d508c686f633be14/map_creator/src/load_reachability_map.cpp#L38) and recompile.

If I'm not mistaken, a preceeding slash is a namespacing functionality in TF1, which is deprecated in TF2.

**Comment by jontromanab** [comment]
A lot of stuffs have changed from TF1 to TF2. So I am not sure if this is still going to work. But @Erixar , Can you please confirm the solutions provided here resolved your problem?

**Comment by MShields1986** [comment]
Applied @juntuck's fix in my fork's noetic branch and it now loads the provided maps OK.

**Comment by liyuping0906** [comment]
@jontromanab  Hello. Can you ask how you managed to compile on neotic? I'm having a lot of issues compiling on neotic. I would appreciate your help
